version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=helpdesk
      - MYSQL_USER=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local